name: Lint code

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.10.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint all code
        run: npm run prettier && npm run lint

      - name: Typecheck all code
        run: npm run typecheck
